
url: http://www.polkadot.network
description: decentralised internet where independent blockchains are exchanging information and enable trust-free transactions via smart contracts, with the key enabling tenets of scalability, governance and inter-operability.
permalink: pretty
exclude:
- Gruntfile.js
- Gemfile
- Gemfile.lock
- package.json
- README*
- node_modules
- ".gitignore"
gems:
- jekyll-seo-tag
- jekyll-sitemap
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
excerpt_separator: |2+



sass:
  sass_dir: styles/
  style: compressed
per_page: 12
date_format: "%b %d, %Y"
google_analytics: UA-1666437-33
twitter:
  username: Polkadot
logo: "/assets/avatar.svg"
future: true
